export function exportReport({
  metrics,
  domainData,
  companyData
}) {
  const report = `
NETWORKOS NETWORK REPORT
========================

NETWORK SUMMARY
---------------
Connections: ${metrics.connections || 0}
Companies: ${metrics.companies || 0}
High Priority Contacts: ${metrics.high || 0}
Mentors: ${metrics.mentors || 0}
Recruiters: ${metrics.recruiters || 0}
Reply Rate: ${metrics.replyRate || 0}%

TOP DOMAIN
----------
${domainData?.[0]?.name || "N/A"}
(${domainData?.[0]?.value || 0} contacts)

TOP COMPANY
-----------
${companyData?.[0]?.name || "N/A"}
(${companyData?.[0]?.value || 0} contacts)

NETWORK HEALTH
--------------
This report was generated by NetworkOS.

Focus Areas:
- Build mentor relationships
- Increase recruiter reach
- Strengthen high-value connections
- Improve reply rate

Generated Locally
Privacy First
`;

  const blob = new Blob(
    [report],
    { type: "text/plain;charset=utf-8" }
  );

  const link = document.createElement("a");

  link.href = URL.createObjectURL(blob);

  link.download =
    "networkos_report.txt";

  link.click();

  URL.revokeObjectURL(link.href);
}